# Generated by Django 6.0.5 on 2026-05-16 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('description', models.TextField(max_length=240)),
                ('location', models.CharField(max_length=90)),
                ('activity_type', models.CharField(choices=[('food', 'Food'), ('sports', 'Sports'), ('study', 'Study'), ('explore', 'Explore'), ('club', 'Club fair')], max_length=20)),
                ('host_alias', models.CharField(default='Anonymous student', max_length=60)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('vibe_note', models.CharField(blank=True, max_length=120)),
                ('accent', models.CharField(default='#12C6C1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_alias', models.CharField(default='Anonymous plus one', max_length=60)),
                ('chat_expires_at', models.DateTimeField()),
                ('host_agreed', models.BooleanField(default=False)),
                ('guest_agreed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matcher.activitypost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('you', 'You'), ('them', 'Them')], max_length=10)),
                ('body', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='matcher.match')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swiper_alias', models.CharField(default='You', max_length=60)),
                ('direction', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='matcher.activitypost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
