# Generated by Django 5.2.14 on 2026-05-17 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampusLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("dining", "Dining"),
                            ("sports", "Sports"),
                            ("study", "Study"),
                            ("event", "Event"),
                            ("outdoor", "Outdoor"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("area", models.CharField(max_length=80)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["area", "name"],
            },
        ),
        migrations.CreateModel(
            name="ActivityPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("sports", "Sports"),
                            ("study", "Study"),
                            ("club", "Club fair"),
                            ("explore", "Explore"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("expire_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("matched", "Matched"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_posts",
                        to="plusone.campuslocation",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time", "expire_time"],
            },
        ),
        migrations.CreateModel(
            name="LLMLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("parse_post", "Parse post"),
                            ("icebreaker", "Icebreaker"),
                            ("moderation", "Moderation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("input_text", models.TextField()),
                ("output_json", models.JSONField(blank=True, default=dict)),
                ("output_text", models.TextField(blank=True)),
                ("model", models.CharField(blank=True, max_length=80)),
                ("strategy", models.CharField(default="rule_fallback", max_length=80)),
                ("success", models.BooleanField(default=True)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("chatting", "Chatting"),
                            ("agreed", "Agreed to meet"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="chatting",
                        max_length=20,
                    ),
                ),
                ("poster_agreed", models.BooleanField(default=False)),
                ("swiper_agreed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("chat_expires_at", models.DateTimeField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="plusone.activitypost",
                    ),
                ),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "swiper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swiped_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_flagged", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="plusone.match",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Swipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("interested", "Interested"), ("pass", "Pass")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipes",
                        to="plusone.activitypost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=80)),
                ("major", models.CharField(blank=True, max_length=100)),
                ("year", models.CharField(blank=True, max_length=40)),
                ("campus_area", models.CharField(blank=True, max_length=80)),
                ("interests", models.CharField(blank=True, max_length=240)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="activitypost",
            index=models.Index(
                fields=["activity_type", "status"],
                name="plusone_act_activit_c89492_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitypost",
            index=models.Index(
                fields=["start_time", "expire_time"],
                name="plusone_act_start_t_b35943_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitypost",
            index=models.Index(
                fields=["status", "expire_time"], name="plusone_act_status_952aa4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("post", "swiper"), name="unique_match_per_post_swiper"
            ),
        ),
        migrations.AddConstraint(
            model_name="swipe",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_swipe_per_user_post"
            ),
        ),
    ]
