# Generated by Django 5.2.14 on 2026-05-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plusone", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_initial",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
